// Dados extraídos do PDF PIPAS
const pipaData = {
    operacoesProd: [
        { codigo: "107", descricao: "Transp Agua" },
        { codigo: "116", descricao: "Reforma/Manut Terceiro" },
        { codigo: "276", descricao: "Regar Grama/Arvores" },
        { codigo: "277", descricao: "Apoio Combate Incendio" },
        { codigo: "718", descricao: "Hidratar Insumos" },
        { codigo: "1077", descricao: "Transp Cana Muda" },
        { codigo: "1099", descricao: "Transp Maq, Impl" },
        { codigo: "1101", descricao: "Regar Estradas" }
    ],
    centrosCusto: [
        { codigo: "315107", descricao: "REFL - TRANS AGUA" },
        { codigo: "316107", descricao: "PÁTIO - TRANSP AGUA" },
        { codigo: "311107", descricao: "CONST BENF - TRANSP AGUA" },
        { codigo: "312107", descricao: "ESTRADAS - TRANSP AGUA" },
        { codigo: "322107", descricao: "PREPARO - TRANSP AGUA" },
        { codigo: "323107", descricao: "PLANTIO - TRANSP AGUA" },
        { codigo: "324001", descricao: "PREPARO - SOJA" },
        { codigo: "324002", descricao: "PLANTIO - SOJA" },
        { codigo: "324003", descricao: "TRATOS - SOJA" },
        { codigo: "324004", descricao: "COLHEITA - SOJA" },
        { codigo: "331107", descricao: "TRATOS CANA PLANTA - TRANSP AGUA" },
        { codigo: "332107", descricao: "TRATOS CANA SOCA - TRANSP AGUA" },
        { codigo: "342107", descricao: "COLH MEC- REGAR ESTRADAS" },
        { codigo: "369107", descricao: "FERT - TRANSP AGUA" },
        { codigo: "402001", descricao: "INDUSTRIA" },
        { codigo: "325001", descricao: "PREPARO - MILHO" },
        { codigo: "325002", descricao: "PLANTIO - MILHO" },
        { codigo: "325003", descricao: "TRATOS - MILHO" },
        { codigo: "325004", descricao: "COLHEITA - MILHO" },
        { codigo: "326001", descricao: "PREPARO - SORGO" },
        { codigo: "326002", descricao: "PLANTIO - SORGO" },
        { codigo: "326003", descricao: "TRATOS - SORGO" },
        { codigo: "326004", descricao: "COLHEITA - SORGO" },
        { codigo: "327001", descricao: "PREPARO - MILHETO" },
        { codigo: "327002", descricao: "PLANTIO - MILHETO" },
        { codigo: "327003", descricao: "TRATOS - MILHETO" },
        { codigo: "327004", descricao: "COLHEITA - MILHETO" },
        { codigo: "318001", descricao: "PECUARIA" },
        { codigo: "315101", descricao: "REFL - REGAR ESTRADAS" },
        { codigo: "316101", descricao: "PÁTIO - REGAR ESTRADAS" },
        { codigo: "311101", descricao: "CONST BENF - REGAR ESTRADAS" },
        { codigo: "312101", descricao: "ESTRADAS - REGAR ESTRADAS" },
        { codigo: "322101", descricao: "PREPARO DE SOLO - REGAR ESTRADAS" },
        { codigo: "323101", descricao: "PLANTIO - REGAR ESTRADAS" },
        { codigo: "331101", descricao: "TRATOS CANA PLANTA - REGAR ESTRADAS" },
        { codigo: "332101", descricao: "TRATOS CANA SOCA - REGAR ESTRADAS" },
        { codigo: "342101", descricao: "COLHEITA MECANIZADA - REGAR ESTRADAS" },
        { codigo: "369101", descricao: "FERT - REGAR ESTRADAS" },
        { codigo: "304002", descricao: "REFORMA/MAN TERC" },
        { codigo: "315276", descricao: "REFL - REGAR GRAMA ARVORE" },
        { codigo: "316276", descricao: "PÁTIO - REGAR GRAMA ARVORE" },
        { codigo: "311276", descricao: "CONST BENF - REGAR GRAMA ARVORE" },
        { codigo: "312276", descricao: "ESTRADAS - REGAR GRAMA ARVORES" },
        { codigo: "322276", descricao: "PREPARO DE SOLO - REGAR GRAMA ARVORE" },
        { codigo: "323276", descricao: "PLANTIO - REGAR GRAMA ARVORE" },
        { codigo: "331276", descricao: "TRATOS CANA PLANTA - REGAR GRAMA ARVORE" },
        { codigo: "332276", descricao: "TRATOS CANA SOCA - REGAR GRAMA ARVORE" },
        { codigo: "342276", descricao: "COLH MEC - REGAR GRAMA ARVORE" },
        { codigo: "369276", descricao: "FERT - REGAR GRAMA ARVORE" },
        { codigo: "315277", descricao: "REFL - APOIO COMBATE INCENDIO" },
        { codigo: "312277", descricao: "ESTRADAS - APOIO COMBATE INCENDIO" },
        { codigo: "322277", descricao: "PREPARO DE SOLO - APOIO COMBATE INCENDIO" },
        { codigo: "323277", descricao: "PLANTIO - APOIO COMBATE INCENDIO" },
        { codigo: "331277", descricao: "TRATOS CANA PLANTA - APOIO COMBATE INCENDIO" },
        { codigo: "332277", descricao: "TRATOS CANA SOCA - APOIO COMBATE INCENDIO" },
        { codigo: "342277", descricao: "COLHEITA MECANIZADA - APOIO COMBATE INCENDIO" },
        { codigo: "369277", descricao: "FERT - APOIO COMBATE INCENDIO" },
        { codigo: "323077", descricao: "TRANSP CANA MUDA" },
        { codigo: "315099", descricao: "REFL - TRANSP MAQUINA IMPL" },
        { codigo: "316099", descricao: "PATIO - TRANSP MAQUINA IMPL" },
        { codigo: "311099", descricao: "CONST BENF - TRANSP MAQUINA IMPL" },
        { codigo: "312099", descricao: "ESTRADAS - TRANSP MAQUINA IMPL" },
        { codigo: "322099", descricao: "PREPARO DE SOLO - TRANSP MAQUINA IMPL" },
        { codigo: "323099", descricao: "PLANTIO - TRANSP MAQUINA IMPL" },
        { codigo: "331099", descricao: "TRATOS CANA PLANTA - TRANSP MAQUINA IMPL" },
        { codigo: "332099", descricao: "TRATOS CANA SOCA - TRANSP MAQUINA IMPL" },
        { codigo: "342099", descricao: "COLH MEC - TRANSP MAQUINA IMPL" },
        { codigo: "369099", descricao: "FERT - TRANSP MAQUINA IMPL" },
        { codigo: "304002", descricao: "OFICINA MECANICA" },
        { codigo: "328001", descricao: "Preparo Solo - Forn. Parc" },
        { codigo: "328002", descricao: "Plantio - Forn. Parceiro" },
        { codigo: "328003", descricao: "Tratos Planta - Forn Parc" },
        { codigo: "328004", descricao: "Tratos Soca - Forn. Parc." },
        { codigo: "315718", descricao: "REFL - TRANS AGUA" },
        { codigo: "316718", descricao: "PÁTIO - HIDRATAR INSUMOS" },
        { codigo: "311718", descricao: "CONST BENF - HIDRATAR INSUMOS" },
        { codigo: "312718", descricao: "ESTRADAS - HIDRATAR INSUMOS" },
        { codigo: "322718", descricao: "PREPARO - HIDRATAR INSUMOS" },
        { codigo: "323718", descricao: "PLANTIO - HIDRATAS INSUMOS" },
        { codigo: "331718", descricao: "TRATOS CANA PLANTA - HIDRATAR INSUMOS" },
        { codigo: "332718", descricao: "TRATOS CANA SOCA - HIDRATAR INSUMOS" },
        { codigo: "342718", descricao: "COLH MEC- HIDRATAR INSUMOS" },
        { codigo: "369718", descricao: "FERT - HIDRATAR INSUMOS" },
        { codigo: "302001", descricao: "Gerencia Agricola" },
        { codigo: "329001", descricao: "Graos Usina" }
    ],
    paradas: [
        { codigo: "713", descricao: "Lavagem Industrial" },
        { codigo: "714", descricao: "Abast Agua" },
        { codigo: "715", descricao: "Transf Agua" },
        { codigo: "716", descricao: "Lavagem Maq Impl" },
        { codigo: "717", descricao: "Regar Grama, Arvore" },
        { codigo: "718", descricao: "Hidratar Insumos" },
        { codigo: "720", descricao: "Apoio Pipa Campo" },
        { codigo: "721", descricao: "Apoio Combate Incendio" },
        { codigo: "723", descricao: "Apoio Manutencao" },
        { codigo: "900", descricao: "Refeicao,Cafe" },
        { codigo: "901", descricao: "Abastecimento" },
        { codigo: "902", descricao: "Chuva" },
        { codigo: "903", descricao: "Manut Corret Op" },
        { codigo: "904", descricao: "Vento Orvalho" },
        { codigo: "906", descricao: "Lubr e Abast" },
        { codigo: "908", descricao: "Ag Carregamento" },
        { codigo: "909", descricao: "Parado 2 Ordem" },
        { codigo: "917", descricao: "Ag Comboio" },
        { codigo: "925", descricao: "Troca de Turno" },
        { codigo: "926", descricao: "Falta Operador" },
        { codigo: "929", descricao: "Lavagem" },
        { codigo: "943", descricao: "Equip Encalhado" },
        { codigo: "963", descricao: "Checklist,Bater Pneus" },
        { codigo: "964", descricao: "Ag Seq Trabalho" },
        { codigo: "965", descricao: "Comprimindo Ar" },
        { codigo: "966", descricao: "Ag Lib Trafego" },
        { codigo: "978", descricao: "Engate,Desengate Impl" },
        { codigo: "986", descricao: "Equip em Manut" },
        { codigo: "987", descricao: "Higiene Pessoal" },
        { codigo: "992", descricao: "Ag Descarr" },
        { codigo: "998", descricao: "Ag Dispon Conjunto" }
    ]
};
